language: "perl"
perl:
    - "5.29"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
install:
    - cpanm -v --installdeps --notest .
before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
script:
  - perl Build.PL
  - ./Build build
  - cover -test
after_success:
  - cover -report codecov
branches:
    only:
        - master
notifications:
    email:
        on_success: change
        on_failure: always
        recipients:
            - andrew@topdog.za.net
