language: "perl"
perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
install:
    - cpanm -v --installdeps --notest .
script: "perl Build.PL; ./Build test"
notifications:
    email:
        on_success: change
        on_failure: always
        recipients:
            - andrew@topdog.za.net
